version: '3'
services:

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: DockerFile
    environment:
      - ACTIVE_PROFILE=${ACTIVE_PROFILE:-dev}
    expose:
      - "8080"
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 80M

volumes:
  grafana-storage: