

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
    defer-datasource-initialization: false
    show-sql: false
    open-in-view: false
  datasource:
    hikari:
      connectionTimeout: '30000'
      maximum-pool-size: '8'
      max-lifetime: '1800000'
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: ${AI_MODEL}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000

tour:
  api-key: ${TOUR_API_KEY}

email:
  host: ${EMAIL_HOST}
  sender: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}

service-url: ${SERVICE_URL}

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    access-token-uri: ${GOOGLE_ACCESS_TOKEN_URI}
    profile-uri: ${GOOGLE_PROFILE_URI}

